const CurrentUserActionTypes = {
    FETCH_CURRENTUSER_START: 'FETCH_CURRENTUSER_START',
    FETCH_CURRENTUSER_SUCCESS: 'FETCH_CURRENTUSER_SUCCESS',
    FETCH_CURRENTUSER_FAILURE: 'FETCH_CURRENTUSER_FAILURE',
    UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
    SET_TOKEN: 'SET_TOKEN',
};

export default CurrentUserActionTypes;
