const CurrentPostsActionTypes = {
    FETCH_CURRENTPOSTS_START: 'FETCH_CURRENTPOSTS_START',
    FETCH_CURRENTPOSTS_SUCCESS: 'FETCH_CURRENTPOSTS_SUCCESS',
    FETCH_CURRENTPOSTS_FAILURE: 'FETCH_CURRENTPOSTS_FAILURE',
};
export default CurrentPostsActionTypes;
