const UserForPostTypes = {
    FETCH_USERFORPOST_START: 'FETCH_USERFORPOST_START',
    FETCH_USERFORPOST_SUCCESS: 'FETCH_USERFORPOST_SUCCESS',
    FETCH_USERFORPOST_FAILURE: 'FETCH_USERFORPOST_FAILURE',
};

export default UserForPostTypes;
